### ISSUE TITLE
Error while running train.py - wrong dimension of padding_eliminator

### ISSUE THREAD

**Issue by nhups** [adammj/ecg-sleep-staging#4] opened 2024-09-26 16:55 UTC
I have created a .h5 file according to the specifics and I am running `python train.py your_datafile.h5`.

It passes all checks at the beginning. However, I get the following error:

```
has argument
your_datafile.h5
preparing...
cuda is not available, using cpu
using device:  cpu
create large temp variable on device
create datasets...
evaluation (validation or testing) set:
there are 1 files:
checking: 100%|████████████████████| 1/1 [00:00<00:00, 19.71it/s]
create data loaders...
delete temp variable
create model...
downsample:  44 25 DenseBlockRes
downsample:  44 25 LayeredDenseBlockRes
downsample:  25 5 DenseBlockRes
downsample:  25 5 LayeredDenseBlockRes
calculate adaptive pools manually:
ecg      input: 91  output: 25  stride: 3  kernel: 19
weight checks:
  count of zeros: 0  ones: 0
  max weight: 3.0146  min: -2.5685
model parameters: 45675
create criterion, optimizer, and scheduler...
learning rate: 0.001
load checkpoint file:  epoch_0647_kappa_0.724.pt
keys: dict_keys(['epoch', 'model_state_dict', 'optimizer_state_dict', 'scheduler_state_dict', 'val_kappa', 'val_loss', 'learning_rate', 'subject_weights'])
set basics...
set model state dict...
set optimizer state dict...
set scheduler state dict...
resuming from checkpoint file...
begin training and evaluation...
----------------------------------------------------------------------
epoch:  648/1000   elapsed: 0:00:01
evaluating... 
evaluating:   0%|                    | 0/1 [00:00<?, ?it/s, k=-0]
evaluating:   0%|                    | 0/1 [00:00<?, ?it/s, k=-0]
Traceback (most recent call last):
  File "/ecg-sleep-staging-main/your_own_data/primary_model/train.py", line 661, in <module>
    main()
  File "/ecg-sleep-staging-main/your_own_data/primary_model/train.py", line 656, in main
    experiment.run_main_loop()
  File "/ecg-sleep-staging-main/your_own_data/primary_model/train.py", line 463, in run_main_loop
    self.eval_stats = self.train_or_eval(
                      ^^^^^^^^^^^^^^^^^^^
  File "/ecg-sleep-staging-main/your_own_data/primary_model/train.py", line 548, in train_or_eval
    model_output, _ = self.model.forward_with_dict(batch_data)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ecg-sleep-staging-main/your_own_data/primary_model/sleepnet.py", line 660, in forward_with_dict
    return self.forward(
           ^^^^^^^^^^^^^
  File "/ecg-sleep-staging-main/your_own_data/primary_model/sleepnet.py", line 631, in forward
    features_out = out * padding_eliminator.expand(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: The expanded size of the tensor (1) must match the existing size (801) at non-singleton dimension 1.  Target sizes: [1, 1, 25].  Tensor sizes: [1, 801, 1]
```

I tried other .h5 files as well as with the other two models, but I always have the same error.

I am creating the .h5 file with this code:

```
    with h5py.File(f'HDF5_PHASE1/{edf_file.stem}.h5', 'w') as f:
        # Create a dataset for the ECG signal
        ecgds = f.create_dataset('ecgs', data=ecg, dtype='f')
        
        # Create a dataset for the demographics
        demods = f.create_dataset('demographics', data=demographics, dtype='f')
        
        # Create a dataset for the midnight offset
        offsetds = f.create_dataset('midnight_offset', (1, 1), dtype='f')
        offsetds[0][0] = np.array(midnight_offset).reshape(1, 1)[0][0]
        
```

This is how the various datasets are shaped:
```
# ecgs
(733, 7680)
float64

# demographics
(2, 1)
float64

# midnight_offset
<class 'float'>
```

My conda environment details are:

```
# Name                    Version                   Build  Channel
blas                      2.124                  openblas    conda-forge
blas-devel                3.9.0           24_osxarm64_openblas    conda-forge
bzip2                     1.0.8                h99b78c6_7    conda-forge
c-ares                    1.33.1               hd74edd7_0    conda-forge
ca-certificates           2024.8.30            hf0a4a13_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
dataclasses-json          0.6.7              pyhd8ed1ab_0    conda-forge
filelock                  3.16.1             pyhd8ed1ab_0    conda-forge
fsspec                    2024.9.0           pyhff2d567_0    conda-forge
gmp                       6.3.0                h7bae524_2    conda-forge
gmpy2                     2.1.5           py312h87fada9_2    conda-forge
h5py                      3.11.0          nompi_py312h903599c_102    conda-forge
hdf5                      1.14.3          nompi_hec07895_105    conda-forge
jinja2                    3.1.4              pyhd8ed1ab_0    conda-forge
krb5                      1.21.3               h237132a_0    conda-forge
libabseil                 20240116.2      cxx17_h00cdb27_1    conda-forge
libaec                    1.1.3                hebf3989_0    conda-forge
libblas                   3.9.0           24_osxarm64_openblas    conda-forge
libcblas                  3.9.0           24_osxarm64_openblas    conda-forge
libcurl                   8.10.1               h13a7ad3_0    conda-forge
libcxx                    19.1.0               ha82da77_0    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libev                     4.33                 h93a5062_2    conda-forge
libexpat                  2.6.3                hf9b8971_0    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libgfortran               5.0.0           13_2_0_hd922786_3    conda-forge
libgfortran5              13.2.0               hf226fd6_3    conda-forge
liblapack                 3.9.0           24_osxarm64_openblas    conda-forge
liblapacke                3.9.0           24_osxarm64_openblas    conda-forge
libnghttp2                1.58.0               ha4dd798_1    conda-forge
libopenblas               0.3.27          openmp_h517c56d_1    conda-forge
libprotobuf               4.25.3               hc39d83c_1    conda-forge
libsqlite                 3.46.1               hc14010f_0    conda-forge
libssh2                   1.11.0               h7a5bd25_0    conda-forge
libzlib                   1.3.1                hfb2fe0b_1    conda-forge
llvm-openmp               18.1.8               hde57baf_1    conda-forge
markupsafe                2.1.5           py312h024a12e_1    conda-forge
marshmallow               3.22.0             pyhd8ed1ab_0    conda-forge
mpc                       1.3.1                h8f1351a_1    conda-forge
mpfr                      4.2.1                hb693164_3    conda-forge
mpmath                    1.3.0              pyhd8ed1ab_0    conda-forge
mypy_extensions           1.0.0              pyha770c72_0    conda-forge
ncurses                   6.5                  h7bae524_1    conda-forge
networkx                  3.3                pyhd8ed1ab_1    conda-forge
numpy                     1.26.4          py312h8442bc7_0    conda-forge
openblas                  0.3.27          openmp_h560b219_1    conda-forge
openssl                   3.3.2                h8359307_0    conda-forge
packaging                 24.1               pyhd8ed1ab_0    conda-forge
pandas                    2.2.3           py312hcd31e36_1    conda-forge
pip                       24.2               pyh8b19718_1    conda-forge
python                    3.12.6          h739c21a_1_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-tzdata             2024.2             pyhd8ed1ab_0    conda-forge
python_abi                3.12                    5_cp312    conda-forge
pytorch                   2.3.0           gpu_mps_py312h0aaebbb_101  
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
readline                  8.2                  h92ec313_1    conda-forge
setuptools                75.1.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sleef                     3.7                  h7783ee8_0    conda-forge
sympy                     1.13.2          pypyh2585a3b_103    conda-forge
tk                        8.6.13               h5083fa2_1    conda-forge
tqdm                      4.66.5             pyhd8ed1ab_0    conda-forge
typing_extensions         4.12.2             pyha770c72_0    conda-forge
typing_inspect            0.9.0              pyhd8ed1ab_0    conda-forge
tzdata                    2024a                h8827d51_1    conda-forge
wheel                     0.44.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge
zstd                      1.5.6                hb46c0d2_0    conda-forge
```

**Comment by adammj** [comment] 2024-09-26 20:43
Thank you for catching that. It was caused by a regression that I committed about 2 weeks ago. I've tested the fix on all 3 models, and it should work now.

**Comment by nhups** [comment] 2024-09-26 22:04
Thank you for your prompt response! I confirm it is working now.

**Closed as completed** 2024-09-26 23:45 UTC
